feat(esx_ambulancejob/server/main): Added state bags
esx-framework/esx_ambulancejob pull request #13
Opened 2023-03-07 18:13 UTC by Thekuca

Added a isDead state bag. Will be very useful in the future in other scripts so we don't have to use on player death and on player spawn handlers we can just check by LocalPlayer.state.isDead

2023-04-03 22:59 UTC, PsychoShock commented
You should change to be able to make check on client too.

2023-06-14 00:01 UTC, Gellipapa requested changes

2023-06-14 00:01 UTC, Gellipapa commented on server/main.lua
> +	plyState.isDead = true
I think you should make function and call everywhere and pass source than parameter.

2023-06-14 00:02 UTC, Gellipapa commented
> You should change to be able to make check on client too. This code is only for server state.

@PsychoShock  Thank you for tested.

2023-06-14 00:03 UTC, Gellipapa commented
@Thekuca Hi! Please refactor code and make works both side.

2023-06-20 21:17 UTC, merged

2023-06-20 21:58 UTC, Gellipapa reviewed
Thank you, looks cool.